app/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.HomepageView.as_view(), name="homepage"),
    path("search", views.PostSearchView.as_view(), name="post_search"),
    path("<slug:post>", views.post_single, name="post_single"),
    path("tag/<slug:tag>", views.TagListView.as_view(), name="post_by_tag"),
]

app/blog/forms.py
from django import forms


class PostSearchForm(forms.Form):
    search_field = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["search_field"].widget.attrs.update({"class": "form-control"})

app/templates/base/3-col-template.html
{% extends "./base.html" %}
{% block template %}

<style>
    @media only screen and (min-width: 992px) {
        .col-navbar {
            flex: 0 0 80px;
            display: flex;
            justify-content: center;
            border-right: 1px solid #dee2e6;
            height: 100vh;
        }
    }
</style>


<div class="container" style="max-width: 1500px!important;">
    <div class="row">
        <div class="col-navbar">{% block content-left %}{% endblock %}</div>
        <div class="col-12 col-lg-8 pt-5 px-4 px-md-5">{% block content-mid %}{% endblock %}</div>
        <div class="d-none d-lg-block col-lg-3 pt-5 ps-4 border-start">
            {% include "blog/components/search-bar.html" %}
            {% block content-right %}{% endblock %}
        </div>
        
    </div>
</div>

{% endblock %}

app/templates/base/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Homepage{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" , href="{% static 'css/main.css' %}">

</head>

<body>
    {% block template %}
    {% endblock %}
    <script src="https://unpkg.com/htmx.org@1.8.4"
        integrity="sha384-wg5Y/JwF7VxGk4zLsJEcAojRtlVp1FKKdGy1qN+OMtdq72WRvX/EdRdqg/LOhYeV"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/base/footer.html
<style>
    .footer .nav-link {
        padding: 0px 10px 5px 0px;
    }

    .footer a {
        color: inherit;
    }
</style>

<footer>
    <ul class="nav fw-500 fs-12 footer">
        <li class="nav-item">
            <a class="nav-link" href="#">Help</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Status</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Writers</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Blog</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Careers</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Privacy</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Terms</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">About</a>
        </li>
    </ul>
</footer>

app/templates/base/navbar.html
<nav class="navbar navbar-expand-lg">
    <div class="container">

        <a class="navbar-brand logo fs-3" href="#">djblogger</a>


        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>



        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            </ul>

            <form method="get" action="/search" class="col-12 pb-5 mb-lg-0">
                <input type="text" name="search_field" class="form-control rounded-pill" placeholder="Search..." id="id_search_field">
            </form>

        </div>

    </div>
</nav>

app/templates/base/secondary-navbar.html
<style>
    #sm-logo-out {
        position: relative;
        background-color: #000;
        width: 38px;
        height: 38px;
        top: 50%;
    }

    #sm-logo-in {
        position: relative;
        background-color: #fff;
        width: 12px;
        height: 12px;
        top: 18%;
        left: 50%
    }

    @media only screen and (max-width: 768px) {

        .container,
        .container-sm {
            max-width: 100%;
        }
    }
</style>

<nav class="navbar navbar-expand-lg py-1 align-items-start pt-lg-4 sticky-top">
    <div class="container py-2 sticky-top">
        <a class="navbar-brand m-0" href="/">
            <div id="sm-logo-out">
                <div id="sm-logo-in">
                </div>
            </div>
        </a>
    </div>
</nav>